Add Locale Switching
wmde/fundraising-application pull request #2227
Opened 2021-06-28 11:35 UTC by Abban

This adds backend functionality for swapping locales and a new soft dependency in the FunFunFactory

Ticket: https://phabricator.wikimedia.org/T256612

2021-06-28 15:28 UTC, gbirke requested changes
While we saw that `StoreLocale` was implicitly tested in our E2E test, please create a separate unit test that tests the fallback mechanism.

2021-06-28 15:28 UTC, gbirke commented on app/EventHandlers/StoreLocale.php
> +		return $request->getPreferredLanguage();
```suggestion
		return $request->getPreferredLanguage() ?? '';
```

2021-06-28 15:57 UTC, gbirke commented on src/Factories/FunFunFactory.php
> +			'locale' => $this->getLocale(),
You can drop this, locale can now be determined on the client side.

2021-06-28 15:57 UTC, gbirke commented on src/Factories/FunFunFactory.php
> +				'locale' => $this->getLocale(),
You can drop this, locale can now be determined on the client side.

2021-06-29 16:14 UTC, gbirke approved these changes

2021-06-29 16:15 UTC, gbirke commented
For a successful deploy, please make a PR in fundraising-infrastructure that removes the `locale` key from the configs

2021-06-30 08:25 UTC, Abban commented
> For a successful deploy, please make a PR in fundraising-infrastructure that removes the `locale` key from the configs

Locale is defaulted by the dist config and not overridden by the ones in infrastructure AFAICT

2021-07-07 11:08 UTC, merged