Allow donation address to be updated
wmde/fundraising-application pull request #2636
Opened 2023-01-03 13:58 UTC by Abban

Also removes deprecated newsletter and receipt opt-ins.

Ticket: https://phabricator.wikimedia.org/T316632

2023-01-06 16:22 UTC, moiikana approved these changes

2023-01-09 09:48 UTC, gbirke requested changes
We are striving to remove the test templates (a leftover from the old PHP-webapp-centered days), see https://phabricator.wikimedia.org/T163452

Please take the opportunity to change the tests and delete the template files.

2023-01-09 14:37 UTC, moiikana commented
there is also a test missing here that needs to be fixed, related to that:
UpdateDonorRouteTest::testWhenDonationAlreadyHasAddress_requestIsDenied
the assertion needs to assume false

2023-01-09 14:39 UTC, Abban commented
> there is also a test missing here that needs to be fixed

Huh, I deleted that already and it came back.

2023-01-09 15:17 UTC, Abban commented
Oh I see, it is deleted. We no longer need that test though, as we don't have that functionality there's no branch to test anymore.

2023-01-10 10:31 UTC, gbirke approved these changes

2023-01-10 10:49 UTC, gbirke commented on skins/test/templates/Donation_Confirmation.html.twig
> +{% if donation.newsletter == true %}
You can delete this file now as well

2023-01-10 12:01 UTC, merged