Donation form test 01
wmde/fundraising-application pull request #2840
Opened 2023-09-12 08:23 UTC by Abban

2023-09-18 14:10 UTC, gbirke requested changes
If we quickly need to deploy this to make the test work, you can consider this as approved. But we then should address my comments as a follow-up

2023-09-18 14:10 UTC, gbirke commented on composer.json
> +		"wmde/fundraising-donations": "dev-test",
Interesting, shouldn't that be `dev-company-with-contact`?

2023-09-18 14:10 UTC, gbirke commented on app/Controllers/Donation/AddDonationController.php
> +
This hack should go into `getSafeDonorType` IMHO, with a comment or maybe even with a restructuring of that code so we know what's going on.

2023-09-18 14:10 UTC, gbirke commented on app/Controllers/Validation/ValidateAddressController.php
> +			}
This check should go into `getCompanyViolations` to avoid 2 levels of nesting here

2023-09-18 14:25 UTC, gbirke approved these changes

2023-09-21 08:26 UTC, moiikana commented
needs to point to fundraising-donations v14.1

2023-09-25 09:21 UTC, moiikana approved these changes

2023-09-25 09:21 UTC, merged